<a href="https://colab.research.google.com/github/yingji15/ipython-notebooks/blob/master/knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import operator

In [0]:
def create_data():
    group = np.array([[1.0,1.1],[1.0,1.0],[0,0],[0,0.1]])
    labels = ['A','A','B','B']
    return group,labels

In [0]:
group,labels = create_data()

In [9]:
group

array([[1. , 1.1],
       [1. , 1. ],
       [0. , 0. ],
       [0. , 0.1]])

In [10]:
labels

['A', 'A', 'B', 'B']

In [0]:
def classify0(x,data,labels,k):
  datasize = data.shape[0] # number of samples in training
  diffmat = np.tile(x,(datasize,1))-data # tile: repeat x rep times, each time a new column, then minus data to prepare for distance 
  sqdiffmat = diffmat**2 # square (x1 - x2)
  sqdistances = sqdiffmat.sum(axis=1) # sum by column (x1-x2)^2 + (y1-y2)^2
  distances = sqdistances**0.5 
  sorted_ind = distances.argsort()
  classCount = {}
  for i in range(k):
    vote = labels[sorted_ind[i]]
    classCount[vote] = classCount.get(vote,0)+1 # get(key,value): if key not there, return value 0
  sortedclasscount = sorted(classCount.items(), key=operator.itemgetter(1),reverse=True)
  return sortedclasscount[0][0]

In [18]:
classify0([0,0],group,labels,3)

'B'

In [19]:
group.shape[0]

4

In [22]:
np.tile([0,0],(4,1))

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [23]:
group

array([[1. , 1.1],
       [1. , 1. ],
       [0. , 0. ],
       [0. , 0.1]])

In [0]:
diffmat = np.tile([0,0],(4,1))-group

In [0]:
sq = diffmat**2
sqd = sq.sum(axis=1)

In [29]:
sq

array([[1.  , 1.21],
       [1.  , 1.  ],
       [0.  , 0.  ],
       [0.  , 0.01]])

In [28]:
sqd

array([2.21, 2.  , 0.  , 0.01])

In [0]:
dist = sqd**0.5
sorted_ind = dist.argsort() # nearest: 0 distance, index 3

In [32]:
classCount = {}
for i in range(3):
  vote = labels[sorted_ind[i]]
  print(i)
  print(sorted_ind[i])
  print(vote)
  classCount[vote] = classCount.get(vote,0) + 1 # it is a counter: note how many times 


0
2
B
1
3
B
2
1
A


In [0]:
sorted_class = sorted(classCount.items(),key=operator.itemgetter(1),reverse=True)

In [36]:
sorted_class

[('B', 2), ('A', 1)]

In [37]:
sorted_class[0]

('B', 2)